module Problem2

(*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*)

let fib() =
    Seq.unfold
        (fun (cur, nxt) -> Some(cur, (nxt, nxt + cur)))
        (0, 1)

let result =
    fib()
    |> Seq.takeWhile (fun n -> n < 4000000) // limit
    |> Seq.filter (fun n -> n % 2 = 0) // is even?
    |> Seq.sum